mail:
    path: /mail
    controller: App\Controller\MailController::welcomeuser
calendario:
    path: /
    controller: App\Controller\CalendarController::index
admin:
    path: /admin/
    controller: App\Controller\AdminController::index
eventedit:
    path: /admin/event/edit/{idedit}
    controller: App\Controller\AdminController::eventedit
    requirements:
        id: '\d+'
eventremove:
    path: admin/event/remove/{id}
    controller: App\Controller\AdminController::removeevent
    requirements:
        id: '\d+'

topicall:
    path: /admin/topic/
    controller: App\Controller\AdminController::alltopic
topic:
    path: /admin/topic/new
    controller: App\Controller\AdminController::topic
topicedit:
    path: /admin/topic/edit
    controller: App\Controller\AdminController::topicedit
topicmodify:
    path: /admin/topic/modify/{id}
    controller: App\Controller\AdminController::topicmodify
topicremove:
    path: admin/topic/remove/{id}
    controller: App\Controller\AdminController::topicremove
    requirements:
        id: '\d+'
teacher:
    path: /admin/teacher/new
    controller: App\Controller\AdminController::teacher
teacheredit:
    path: /admin/teacher/edit
    controller: App\Controller\AdminController::teacheredit
teachermodify:
    path: /admin/teacher/modify/{id}
    controller: App\Controller\AdminController::teachermodify
teacherremove:
    path: admin/teacher/remove/{id}
    controller: App\Controller\AdminController::removeteacher
    requirements:
        id: '\d+'
teacherall:
    path: /admin/teacher
    controller: App\Controller\AdminController::allteacher

typeall:
    path: /admin/type
    controller: App\Controller\AdminController::alltype
type:
    path: /admin/type/new
    controller: App\Controller\AdminController::type
typeedit:
    path: /admin/type/edit
    controller: App\Controller\AdminController::typeedit
typeremove:
    path: admin/type/remove/{id}
    controller: App\Controller\AdminController::removetype
    requirements:
        id: '\d+'

place:
    path: /admin/place
    controller: App\Controller\AdminController::place
placeedit:
    path: /admin/place/edit
    controller: App\Controller\AdminController::placeedit
placeremove:
    path: admin/place/remove/{id}
    controller: App\Controller\AdminController::removeplace
    requirements:
        id: '\d+'
placeall:
    path: /admin/place/all
    controller: App\Controller\AdminController::allplace
user:
    path: /admin/user
    controller: App\Controller\AdminController::user
useredit:
    path: /admin/useredit
    controller: App\Controller\AdminController::useredit
userremove:
    path: /user/remove/{id}
    controller: App\Controller\AdminController::removeuser
    requirements:
        id: '\d+'
userall:
    path: /admin/user/all
    controller: App\Controller\AdminController::alluser

usertype:
    path: /admin/usertype/
    controller: App\Controller\AdminController::usertype
viewusertype:
    path: /admin/viewusertype/
    controller: App\Controller\AdminController::viewusertype
editusertype:
    path: /admin/editusertype/{id}
    controller: App\Controller\AdminController::editusertype
    requirements:
        id: '\d+'
removeusertype:
    path: /admin/removeusertype/{id}
    controller: App\Controller\AdminController::removeusertype
    requirements:
        id: '\d+'
login:
    path: /login
    controller: App\Controller\SecurityController::login
recoverpassword:
    path: /recoverpassword
    controller: App\Controller\AdminController::recoverpassword
recoverpasswordurl:
    path: /recoverpassword/{keyurl}
    controller: App\Controller\AdminController::changepassword
logout:
    path: /logout
